name       : linux-firmware
version    : 20211202
release    : 55
source     :
    - git|https://kernel.googlesource.com/pub/scm/linux/kernel/git/firmware/linux-firmware.git : b0e898fbaf377c99a36aac6fdeb7250003648ca4
license    :
    - GPL-2.0-or-later
    - Distributable
component  : kernel
summary    : Firmware required for many devices
description: |
    Free and non-free firmware required for enablement of many devices and hardware
strip      : no
rundeps    :
    - intel-microcode
install    : |
    %make_install

    # Remove blacklisted
    for i in carl9170fw netronome liquidio qed Makefile GPL-3; do
        rm -rvf $installdir/lib/firmware/$i
    done

    # Stick docs in
    install -dDm00755 $installdir/usr/share/doc/${package}
    install -m00644 LICENSE* $installdir/usr/share/doc/${package}/.
    install -m00644 LICENCE* $installdir/usr/share/doc/${package}/.
