name       : linux-firmware
version    : 20180118
release    : 21
source     :
    - git|git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git : 2a713be25a44bd6cec90d8affc54b246a2ca9c7b
license    :
    - GPL-2.0+
    - Distributable
summary    : Firmware required for many devices
component  : kernel
strip      : no
description: |
    Free and non-free firmware required for enablement of many devices and hardware
install    : |
    %make_install

    # Remove blacklisted
    for i in carl9170fw Makefile GPL-3; do
        rm -rvf $installdir/lib/firmware/$i
    done

    # Stick docs in
    install -d -D -m 00755 $installdir/usr/share/doc/${package}
    install -m 00644 LICENSE* $installdir/usr/share/doc/${package}/.
    install -m 00644 LICENCE* $installdir/usr/share/doc/${package}/.
