name       : linux-firmware
version    : 20200122
release    : 46
source     :
    - git|git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git : 04e0b4cf4caee531448671c8a836223f05b72ba6
license    :
    - GPL-2.0-or-later
    - Distributable
summary    : Firmware required for many devices
component  : kernel
strip      : no
description: |
    Free and non-free firmware required for enablement of many devices and hardware
rundeps    :
    - intel-microcode
install    : |
    %make_install

    # Remove blacklisted
    for i in carl9170fw netronome liquidio qed Makefile GPL-3; do
        rm -rvf $installdir/lib/firmware/$i
    done

    # Stick docs in
    install -dDm00755 $installdir/usr/share/doc/${package}
    install -m00644 LICENSE* $installdir/usr/share/doc/${package}/.
    install -m00644 LICENCE* $installdir/usr/share/doc/${package}/.
