name       : linux-firmware
version    : 20230625
release    : 64
source     :
    - git|https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git : 20230625
license    :
    - GPL-2.0-or-later
    - Distributable
component  : kernel
summary    : Firmware required for many devices
description: |
    Free and non-free firmware required for enablement of many devices and hardware
strip      : no
rundeps    :
    - intel-microcode
setup      : |
    git config --global user.email "solus@getsol.us"
    git config --global user.name "Solus"

    # https://gitlab.freedesktop.org/drm/amd/-/issues/2666
    git cherry-pick d3f66064cf43bd7338a79174bd0ff60c4ecbdf6d

    # CVE-2023-20593 (Zenbleed)
    git cherry-pick b250b32ab1d044953af2dc5e790819a7703b7ee6
    git cherry-pick 0bc3126c9cfa0b8c761483215c25382f831a7c6f
install    : |
    %make_install

    # Remove blacklisted
    for i in carl9170fw netronome liquidio qed Makefile GPL-3; do
        rm -rvf $installdir/lib/firmware/$i
    done

    # Stick docs in
    install -dDm00755 $installdir/usr/share/doc/${package}
    install -m00644 LICENSE* $installdir/usr/share/doc/${package}/.
    install -m00644 LICENCE* $installdir/usr/share/doc/${package}/.
