name       : linux-firmware
version    : 20190312
release    : 37
source     :
    - git|git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git : b0d9583f9528890dfcb28d338fe70b50371084bf
license    :
    - GPL-2.0-or-later
    - Distributable
summary    : Firmware required for many devices
component  : kernel
strip      : no
description: |
    Free and non-free firmware required for enablement of many devices and hardware
install    : |
    %make_install

    # Remove blacklisted
    for i in carl9170fw netronome liquidio qed Makefile GPL-3; do
        rm -rvf $installdir/lib/firmware/$i
    done

    # Stick docs in
    install -d -D -m 00755 $installdir/usr/share/doc/${package}
    install -m 00644 LICENSE* $installdir/usr/share/doc/${package}/.
    install -m 00644 LICENCE* $installdir/usr/share/doc/${package}/.
