name       : linux-firmware
version    : 20230804
release    : 65
source     :
    - git|https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git : 20230804
license    :
    - GPL-2.0-or-later
    - Distributable
component  : kernel
summary    : Firmware required for many devices
description: |
    Free and non-free firmware required for enablement of many devices and hardware
strip      : no
rundeps    :
    - intel-microcode
setup      : |
    git config --global user.email "solus@getsol.us"
    git config --global user.name "Solus"

    # Fixes a Realtek bluetooth adapter
    git cherry-pick 7ed62638b50f3954099c6bb23f7121cb2a5b0048
    git cherry-pick 42d31f8f6ed64f5508f10d09451f60d524107ee0

    # CVE-2023-20569 (AMD Inception)
    git cherry-pick f2eb058afc57348cde66852272d6bf11da1eef8f
install    : |
    %make_install

    # Remove blacklisted
    for i in carl9170fw netronome liquidio qed Makefile GPL-3; do
        rm -rvf $installdir/lib/firmware/$i
    done

    # Stick docs in
    install -dDm00755 $installdir/usr/share/doc/${package}
    install -m00644 LICENSE* $installdir/usr/share/doc/${package}/.
    install -m00644 LICENCE* $installdir/usr/share/doc/${package}/.
